In [1]:
import pandas as pd
import plotly.express as px
import seaborn as sns
import plotly as plt

In [45]:
df = pd.read_csv(
    "/Users/dayaneribeiro/Documents/Spiced/da-capstone-project-dayane-ernesto/Cleaned Sets/Aggregated_Table_Prevalence_Consumption_Abstention.csv"
)
df

,location,sex,age,year,percent_of_prevalence,upper,lower,Liters Pure Alcohol Consumed,consumption_in_liters_per_capita,Min,Max,% of Pop. Abstainers,percent_of_abstainers,Min_Abstention,Max_Abstention
0,Albania,Male,15-19 years,2005,0.009183,0.014542,0.005085,4.5 [3.5 - 5.6],4.54992,3.481704,5.561019,49.7 [47.5 - 51.9],49.713805,47.544030,51.883579
1,Albania,Male,15-19 years,2005,0.009183,0.014542,0.005085,4.5 [3.5 - 5.6],4.54992,3.481704,5.561019,61.3 [59.1 - 63.6],61.340818,59.063788,63.617849
2,Albania,Male,15-19 years,2005,0.009183,0.014542,0.005085,4.5 [3.5 - 5.6],4.54992,3.481704,5.561019,37.7 [35.6 - 39.8],37.716065,35.628734,39.803396
3,Albania,Female,15-19 years,2005,0.006313,0.010442,0.003289,4.5 [3.5 - 5.6],4.54992,3.481704,5.561019,49.7 [47.5 - 51.9],49.713805,47.544030,51.883579
4,Albania,Female,15-19 years,2005,0.006313,0.010442,0.003289,4.5 [3.5 - 5.6],4.54992,3.481704,5.561019,61.3 [59.1 - 63.6],61.340818,59.063788,63.617849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49435,Poland,Male,40-44 years,2013,0.013032,0.017737,0.008895,10.5 [8.8 - 12.2],10.49000,8.837387,12.236145,18.4 [17.4 - 19.4],18.369657,17.384715,19.354598
49436,Poland,Male,40-44 years,2013,0.013032,0.017737,0.008895,10.5 [8.8 - 12.2],10.49000,8.837387,12.236145,26.7 [25.4 - 28.1],26.712777,25.368298,28.057256
49437,Poland,Female,40-44 years,2013,0.006509,0.008951,0.004507,10.5 [8.8 - 12.2],10.49000,8.837387,12.236145,34.4 [32.7 - 36.1],34.382079,32.692822,36.071336
49438,Poland,Female,40-44 years,2013,0.006509,0.008951,0.004507,10.5 [8.8 - 12.2],10.49000,8.837387,12.236145,18.4 [17.4 - 19.4],18.369657,17.384715,19.354598
49439,Poland,Female,40-44 years,2013,0.006509,0.008951,0.004507,10.5 [8.8 - 12.2],10.49000,8.837387,12.236145,26.7 [25.4 - 28.1],26.712777,25.368298,28.057256

In [46]:
df.rename(columns={"consumption_in_liters_per_capita": "Consumption per Capita (Liters)", "location": "Country"}, inplace=True)

In [47]:
df_clean = df.groupby(
    ["Country", "age", "year", "sex"],
    as_index=False
)["Consumption per Capita (Liters)"].mean()

In [49]:
fig = px.line(
    df_clean,
    x="year",
    y="Consumption per Capita (Liters)",
    color="Country",
    title="Alcohol Consumption Over Time"
)
fig.update_yaxes(rangemode="tozero")
fig.show()

In [51]:
countries = ["Germany", "Ireland"]

df_subset = df_clean[df_clean["Country"].isin(countries)]

fig = px.line(
    df_subset,
    x="year",
    y="Consumption per Capita (Liters)",
    color="Country",
    title="Alcohol Consumption Over Time"
)
#fig.update_yaxes(rangemode="tozero")
fig.show()

In [52]:
df1 = pd.read_csv("/Users/dayaneribeiro/Documents/Spiced/da-capstone-project-dayane-ernesto/Cleaned Sets/consumption_and_prevalence_2005-2020.csv")
df1

,location,age,year,precent_of_prevalence,pre_upper_bound,pre_lower_bound,consumption_in_liters
0,Albania,15-19 years,2005,0.007746,0.012591,0.004332,4.54992
1,Albania,20-24 years,2005,0.021565,0.033490,0.012558,4.54992
2,Albania,25-29 years,2005,0.027626,0.038303,0.018784,4.54992
3,Albania,30-34 years,2005,0.028825,0.043374,0.017788,4.54992
4,Albania,35-39 years,2005,0.025798,0.036498,0.017049,4.54992
...,...,...,...,...,...,...,...
5011,United Kingdom,20-24 years,2023,0.040710,0.056886,0.028569,NaN
5012,United Kingdom,25-29 years,2023,0.047753,0.062016,0.035855,NaN
5013,United Kingdom,30-34 years,2023,0.048562,0.063295,0.034594,NaN
5014,United Kingdom,35-39 years,2023,0.049123,0.060955,0.038354,NaN
5015,United Kingdom,40-44 years,2023,0.048010,0.061964,0.037021,NaN

In [53]:
df1["precent_of_prevalence"] = df1["precent_of_prevalence"] * 100
df1.head()

,location,age,year,precent_of_prevalence,pre_upper_bound,pre_lower_bound,consumption_in_liters
0,Albania,15-19 years,2005,0.774575,0.012591,0.004332,4.54992
1,Albania,20-24 years,2005,2.156544,0.033490,0.012558,4.54992
2,Albania,25-29 years,2005,2.762616,0.038303,0.018784,4.54992
3,Albania,30-34 years,2005,2.882462,0.043374,0.017788,4.54992
4,Albania,35-39 years,2005,2.579800,0.036498,0.017049,4.54992

In [54]:
df1.rename(columns={"precent_of_prevalence": "Prevalence", "location": "Country"}, inplace=True)

In [56]:
fig = px.choropleth(
    df1,
    #df1_clean.sort_values(by="NumericValue", ascending=False),
    locations="Country", 
    locationmode="country names",        
    color="Prevalence",
    hover_name="Country",
    #hover_data="year",
    #hover_data="age",
    color_continuous_scale="RdYlBu",
    #range_color=(0, 1),
    title="AUD prevalence by Country"
)
fig.update_geos(
    #scope="europe",
    projection_scale=2.5,
    center={"lat": 54, "lon": 15} 
)
fig.show()

/var/folders/s4/_zhd9zj1105fnq7y281mkzdc0000gn/T/ipykernel_7444/990213872.py:1: DeprecationWarning: The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.
  fig = px.choropleth(

In [64]:
df1["age_year"] = df1["age"] + " | " + df1["year"].astype(str)

fig = px.choropleth(
    df1,
    locations="Country",
    locationmode="country names",
    color="Prevalence",
    hover_name="Country",
    animation_frame="age_year", 
    color_continuous_scale="RdYlBu",
    title="AUD prevalence by Country and Age"
)
fig.update_geos(
    #scope="europe",
    projection_scale=2.5,
    center={"lat": 54, "lon": 15} 
)
#fig.layout.sliders[0].transition.duration = 2000
fig.show()


# try to add year as a filter for this graph

/var/folders/s4/_zhd9zj1105fnq7y281mkzdc0000gn/T/ipykernel_7444/875576538.py:3: DeprecationWarning: The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.
  fig = px.choropleth(

In [27]:
gen_analysis = pd.read_csv("/Users/dayaneribeiro/Documents/Spiced/da-capstone-project-dayane-ernesto/Cleaned Sets/gen_gap_2019-analysis.csv")
gen_analysis

,location,sex,age,year,precent_of_prevalence,upper_bound,lower_bound
0,Albania,Male,15-19 years,2010,0.009399,0.015126,0.005307
1,Albania,Female,15-19 years,2010,0.006388,0.010502,0.003393
2,Albania,Both Sexes,15-19 years,2010,0.007886,0.012866,0.004241
3,Albania,Male,20-24 years,2010,0.025625,0.040491,0.015240
4,Albania,Female,20-24 years,2010,0.018424,0.029211,0.010647
...,...,...,...,...,...,...,...
805,Italy,Female,35-39 years,2019,0.015842,0.021173,0.011176
806,Italy,Both Sexes,35-39 years,2019,0.025459,0.032900,0.018591
807,Italy,Male,40-44 years,2019,0.029761,0.040194,0.021383
808,Italy,Female,40-44 years,2019,0.012890,0.018061,0.008861
809,Italy,Both Sexes,40-44 years,2019,0.021248,0.029052,0.015345

In [58]:
gen_analysis.rename(columns={"precent_of_prevalence": "Prevalence", "location": "Country"}, inplace=True)

In [60]:
gen_analysis["prevalence"] = gen_analysis["prevalence"] * 100
gen_analysis.head()

,Country,sex,age,year,prevalence,upper_bound,lower_bound,generation
0,Albania,Male,15-19 years,2010,93.992877,0.015126,0.005307,Gen_Z
1,Albania,Female,15-19 years,2010,63.881603,0.010502,0.003393,Gen_Z
2,Albania,Both Sexes,15-19 years,2010,78.856900,0.012866,0.004241,Gen_Z
3,Albania,Male,20-24 years,2010,256.251128,0.040491,0.015240,Gen_Z
4,Albania,Female,20-24 years,2010,184.237103,0.029211,0.010647,Gen_Z

In [31]:

def define_gen(age):
    if '15-19 years' in age or '20-24 years' in age:
        return 'Gen_Z'
    elif '25-29 years' in age or '30-34 years' in age or '35-39 years' in age:
        return 'Millennial'
    else:
        return 'Gen_X'

In [34]:
gen_analysis['generation'] = gen_analysis['age'].apply(define_gen)
gen_analysis.head()

,location,sex,age,year,prevalence,upper_bound,lower_bound,generation
0,Albania,Male,15-19 years,2010,0.939929,0.015126,0.005307,Gen_Z
1,Albania,Female,15-19 years,2010,0.638816,0.010502,0.003393,Gen_Z
2,Albania,Both Sexes,15-19 years,2010,0.788569,0.012866,0.004241,Gen_Z
3,Albania,Male,20-24 years,2010,2.562511,0.040491,0.015240,Gen_Z
4,Albania,Female,20-24 years,2010,1.842371,0.029211,0.010647,Gen_Z

In [37]:
# 3. (Optional but recommended) filter to avoid duplicates across sex
df_filtered = gen_analysis[gen_analysis['sex'] == 'Both Sexes']

# 4. Aggregate mean prevalence by year and generation
grouped = df_filtered.groupby(['year', 'generation'])['prevalence'].mean().reset_index()

# 5. Pivot for plotting
pivot_df = grouped.pivot(index='year', columns='generation', values='prevalence')

In [43]:
fig = px.choropleth(
    gen_analysis,
    locations="location",
    locationmode="country names",
    color="prevalence",
    hover_name="location",
    animation_frame="generation", 
    color_continuous_scale="RdYlBu",
    title="AUD prevalence in Generations"
)
fig.update_geos(
    #scope="europe",
    projection_scale=2.5,
    center={"lat": 54, "lon": 15} 
)
#fig.layout.sliders[0].transition.duration = 2000
fig.show()

/var/folders/s4/_zhd9zj1105fnq7y281mkzdc0000gn/T/ipykernel_7444/2096810095.py:1: DeprecationWarning: The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.
  fig = px.choropleth(