In [28]:
import pandas as pd
import plotly.express as px
import seaborn as sns
import plotly as plt



Maps showing percent of prevalence (adjust column name) per age / country / year
Bar charts showing consumption / prevalence per country / year (age is still aggregated value)

In [ ]:
df = pd.read_csv(
    "/Users/dayaneribeiro/Documents/Spiced/da-capstone-project-dayane-ernesto/Cleaned Sets/abstention_and_prevalence_2005-2020.csv"
)
df

# prevalence: percentage of the population that has AUD (alcohol consumption disorder)

,location,sex,age,year,precent_of_prevalence,upper_bound,lower_bound,population_percentage_abstainers
0,Albania,male,15-19 years,2005,0.009183,0.014542,0.005085,37.716065
1,Albania,female,15-19 years,2005,0.006313,0.010442,0.003289,61.340818
2,Albania,both sexes,15-19 years,2005,0.007746,0.012591,0.004332,49.713805
3,Albania,male,20-24 years,2005,0.025058,0.039093,0.014484,37.716065
4,Albania,female,20-24 years,2005,0.018224,0.029243,0.010444,61.340818
...,...,...,...,...,...,...,...,...
15043,United Kingdom,female,35-39 years,2023,0.020648,0.025918,0.015691,NaN
15044,United Kingdom,both sexes,35-39 years,2023,0.049123,0.060955,0.038354,NaN
15045,United Kingdom,male,40-44 years,2023,0.078855,0.099908,0.060850,NaN
15046,United Kingdom,female,40-44 years,2023,0.019155,0.025240,0.014407,NaN
15047,United Kingdom,both sexes,40-44 years,2023,0.048010,0.061964,0.037021,NaN

In [9]:
df1 = pd.read_csv("/Users/dayaneribeiro/Documents/Spiced/da-capstone-project-dayane-ernesto/Cleaned Sets/consumption_and_prevalence_2005-2020.csv")
df1

,location,age,year,precent_of_prevalence,pre_upper_bound,pre_lower_bound,consumption_in_liters
0,Albania,15-19 years,2005,0.007746,0.012591,0.004332,4.54992
1,Albania,20-24 years,2005,0.021565,0.033490,0.012558,4.54992
2,Albania,25-29 years,2005,0.027626,0.038303,0.018784,4.54992
3,Albania,30-34 years,2005,0.028825,0.043374,0.017788,4.54992
4,Albania,35-39 years,2005,0.025798,0.036498,0.017049,4.54992
...,...,...,...,...,...,...,...
5011,United Kingdom,20-24 years,2023,0.040710,0.056886,0.028569,NaN
5012,United Kingdom,25-29 years,2023,0.047753,0.062016,0.035855,NaN
5013,United Kingdom,30-34 years,2023,0.048562,0.063295,0.034594,NaN
5014,United Kingdom,35-39 years,2023,0.049123,0.060955,0.038354,NaN
5015,United Kingdom,40-44 years,2023,0.048010,0.061964,0.037021,NaN

In [19]:
df1["precent_of_prevalence"] = df1["precent_of_prevalence"] * 100
df1.head()

,location,age,year,precent_of_prevalence,pre_upper_bound,pre_lower_bound,consumption_in_liters
0,Albania,15-19 years,2005,0.774575,0.012591,0.004332,4.54992
1,Albania,20-24 years,2005,2.156544,0.033490,0.012558,4.54992
2,Albania,25-29 years,2005,2.762616,0.038303,0.018784,4.54992
3,Albania,30-34 years,2005,2.882462,0.043374,0.017788,4.54992
4,Albania,35-39 years,2005,2.579800,0.036498,0.017049,4.54992

In [20]:
fig = px.choropleth(
    df1,
    #df1_clean.sort_values(by="NumericValue", ascending=False),
    locations="location", 
    locationmode="country names",        
    color="precent_of_prevalence",
    hover_name="location",
    #hover_data="year",
    #hover_data="age",
    color_continuous_scale="RdYlBu",
    #range_color=(0, 1),
    title="Alcohol Consumption by Country"
)

fig.show()

/var/folders/s4/_zhd9zj1105fnq7y281mkzdc0000gn/T/ipykernel_2806/1705173346.py:1: DeprecationWarning: The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.
  fig = px.choropleth(

In [25]:
df_age = df1[df1["age"] == "15-19 years"]

fig = px.choropleth(
    df_age,
    locations="location",
    locationmode="country names",
    color="precent_of_prevalence",
    hover_name="location",
    color_continuous_scale="RdYlBu",
    title="People with AUD by Country / Age"
)

fig.show()

/var/folders/s4/_zhd9zj1105fnq7y281mkzdc0000gn/T/ipykernel_2806/1988297143.py:3: DeprecationWarning: The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.
  fig = px.choropleth(

In [10]:
df2 = pd.read_csv("/Users/dayaneribeiro/Documents/Spiced/da-capstone-project-dayane-ernesto/Cleaned Sets/master_prevalence_2005_2023.csv")
df2

,location,sex,age,year,precent_of_prevalence,upper_bound,lower_bound
0,Albania,Male,15-19 years,2005,0.009183,0.014542,0.005085
1,Albania,Female,15-19 years,2005,0.006313,0.010442,0.003289
2,Albania,Both Sexes,15-19 years,2005,0.007746,0.012591,0.004332
3,Albania,Male,20-24 years,2005,0.025058,0.039093,0.014484
4,Albania,Female,20-24 years,2005,0.018224,0.029243,0.010444
...,...,...,...,...,...,...,...
15043,United Kingdom,Female,35-39 years,2023,0.020648,0.025918,0.015691
15044,United Kingdom,Both Sexes,35-39 years,2023,0.049123,0.060955,0.038354
15045,United Kingdom,Male,40-44 years,2023,0.078855,0.099908,0.060850
15046,United Kingdom,Female,40-44 years,2023,0.019155,0.025240,0.014407
15047,United Kingdom,Both Sexes,40-44 years,2023,0.048010,0.061964,0.037021

In [11]:
df3 = pd.read_csv("/Users/dayaneribeiro/Documents/Spiced/da-capstone-project-dayane-ernesto/Cleaned Sets/Consumption_in_Europe_2000-2020.csv")
df3

,Title,Year,Liters Pure Alcohol Consumed,NumericValue,Min,Max
0,Azerbaijan,2008,0.6 [0.3 - 1.0],0.568046,0.251125,0.964423
1,Portugal,2012,10.0 [8.4 - 11.7],10.040000,8.401023,11.692693
2,Tajikistan,2020,0.8 [0.3 - 1.2],0.760516,0.340246,1.209908
3,Netherlands (Kingdom of the),2008,9.4 [7.7 - 11.0],9.350000,7.660837,10.963466
4,Portugal,2018,10.6 [9.0 - 12.2],10.553597,8.961007,12.158488
...,...,...,...,...,...,...
1168,Serbia,2020,7.9 [6.3 - 9.2],7.856437,6.258593,9.237920
1169,Georgia,2005,5.4 [4.1 - 6.5],5.366606,4.120049,6.467267
1170,Switzerland,2020,8.6 [7.2 - 10.1],8.630000,7.243281,10.135972
1171,Czechia,2021,13.0 [11.2 - 14.7],12.992705,11.155746,14.701137
1172,Azerbaijan,2017,0.6 [0.2 - 1.0],0.573333,0.220763,0.954461

In [29]:
age = ["15-19 years", "20-24 years"]
year = ["2005"]

df1_subset = df1[df1["age"].isin(age)]
df1_subset = df1[df1["year"].isin(year)]

plt.figure(figsize=(12,6))
sns.barplot(
    data=df1_subset,
    x="year",
    y="age",
    hue="location"
)

plt.xticks(rotation=45)
plt.title("Alcohol Consumption per year")
plt.show()

AttributeError: module 'plotly' has no attribute 'figure'